<?php

//Ruta de error
$map['error']['access'] = Config::$ACCESS_LEVEL_GUEST;
//Ruta de access
$map['access']['access'] = Config::$ACCESS_LEVEL_GUEST;
//Ruta de notsigned
$map['notsigned']['access'] = Config::$ACCESS_LEVEL_GUEST;
//Ruta de notuseragent
$map['notuseragent']['access'] = Config::$ACCESS_LEVEL_GUEST;
//Ruta de projects
$map['projects']['access'] = Config::$ACCESS_LEVEL_USER;
//Ruta de project
$map['project']['access'] = Config::$ACCESS_LEVEL_USER;
//Ruta de 404
$map['404']['access'] = Config::$ACCESS_LEVEL_GUEST;

//Ruta de getProjectsOfUser
$map['getProjectsOfUser']['access'] = Config::$ACCESS_LEVEL_USER;
//Ruta de getProjectDetails
$map['getProjectDetails']['access'] = Config::$ACCESS_LEVEL_USER;
//Ruta de getDashboardsOfProject
$map['getDashboardsOfProject']['access'] = Config::$ACCESS_LEVEL_USER;
//Ruta de getCollaboratorsOfProject
$map['getCollaboratorsOfProject']['access'] = Config::$ACCESS_LEVEL_USER;
//Ruta de bookmarkProject
$map['bookmarkProject']['access'] = Config::$ACCESS_LEVEL_USER;
//Ruta de bookmarkDashboard
$map['bookmarkDashboard']['access'] = Config::$ACCESS_LEVEL_USER;
//Ruta de doesUsernameExists
$map['doesUsernameExists']['access'] = Config::$ACCESS_LEVEL_USER;
//Ruta de doesEmailExists
$map['doesEmailExists']['access'] = Config::$ACCESS_LEVEL_USER;
//Ruta de getListsOfDashboard
$map['getListsOfDashboard']['access'] = Config::$ACCESS_LEVEL_USER;
//Ruta de getCommentsOfDashboardItem
$map['getCommentsOfDashboardItem']['access'] = Config::$ACCESS_LEVEL_USER;

//Ruta de createDashboards
$map['createDashboards']['access'] = Config::$ACCESS_LEVEL_USER;
//Ruta de updateDashboards
$map['updateDashboards']['access'] = Config::$ACCESS_LEVEL_USER;
//Ruta de queryDashboards
$map['queryDashboards']['access'] = Config::$ACCESS_LEVEL_USER;
//Ruta de deleteDashboards
$map['deleteDashboards']['access'] = Config::$ACCESS_LEVEL_USER;

//Ruta de createDashboardItemComments
$map['createDashboardItemComments']['access'] = Config::$ACCESS_LEVEL_USER;
//Ruta de updateDashboardItemComments
$map['updateDashboardItemComments']['access'] = Config::$ACCESS_LEVEL_USER;
//Ruta de queryDashboardItemComments
$map['queryDashboardItemComments']['access'] = Config::$ACCESS_LEVEL_USER;
//Ruta de deleteDashboardItemComments
$map['deleteDashboardItemComments']['access'] = Config::$ACCESS_LEVEL_USER;

//Ruta de signin
$map['signin']['access'] = Config::$ACCESS_LEVEL_GUEST;
//Ruta de signup
$map['signup']['access'] = Config::$ACCESS_LEVEL_GUEST;
//Ruta de signout
$map['signout']['access'] = Config::$ACCESS_LEVEL_GUEST;
//Ruta de signinFunctionality
$map['signinFunctionality']['access'] = Config::$ACCESS_LEVEL_GUEST;

//Ruta de test
$map['test']['access'] = Config::$ACCESS_LEVEL_ADMIN;
//Ruta de createClients
$map['createClients']['access'] = Config::$ACCESS_LEVEL_USER;
//Ruta de updateClients
$map['updateClients']['access'] = Config::$ACCESS_LEVEL_USER;
//Ruta de queryClients
$map['queryClients']['access'] = Config::$ACCESS_LEVEL_USER;
//Ruta de deleteClients
$map['deleteClients']['access'] = Config::$ACCESS_LEVEL_USER;
//Ruta de createCollaborators
$map['createCollaborators']['access'] = Config::$ACCESS_LEVEL_USER;
//Ruta de updateCollaborators
$map['updateCollaborators']['access'] = Config::$ACCESS_LEVEL_USER;
//Ruta de queryCollaborators
$map['queryCollaborators']['access'] = Config::$ACCESS_LEVEL_USER;
//Ruta de deleteCollaborators
$map['deleteCollaborators']['access'] = Config::$ACCESS_LEVEL_USER;
//Ruta de createGlobalLevel
$map['createGlobalLevel']['access'] = Config::$ACCESS_LEVEL_USER;
//Ruta de updateGlobalLevel
$map['updateGlobalLevel']['access'] = Config::$ACCESS_LEVEL_USER;
//Ruta de queryGlobalLevel
$map['queryGlobalLevel']['access'] = Config::$ACCESS_LEVEL_USER;
//Ruta de deleteGlobalLevel
$map['deleteGlobalLevel']['access'] = Config::$ACCESS_LEVEL_USER;
//Ruta de createPermissions
$map['createPermissions']['access'] = Config::$ACCESS_LEVEL_USER;
//Ruta de updatePermissions
$map['updatePermissions']['access'] = Config::$ACCESS_LEVEL_USER;
//Ruta de queryPermissions
$map['queryPermissions']['access'] = Config::$ACCESS_LEVEL_USER;
//Ruta de deletePermissions
$map['deletePermissions']['access'] = Config::$ACCESS_LEVEL_USER;
//Ruta de createProjectDiary
$map['createProjectDiary']['access'] = Config::$ACCESS_LEVEL_USER;
//Ruta de updateProjectDiary
$map['updateProjectDiary']['access'] = Config::$ACCESS_LEVEL_USER;
//Ruta de queryProjectDiary
$map['queryProjectDiary']['access'] = Config::$ACCESS_LEVEL_USER;
//Ruta de deleteProjectDiary
$map['deleteProjectDiary']['access'] = Config::$ACCESS_LEVEL_USER;
//Ruta de createProjects
$map['createProjects']['access'] = Config::$ACCESS_LEVEL_USER;
//Ruta de updateProjects
$map['updateProjects']['access'] = Config::$ACCESS_LEVEL_USER;
//Ruta de queryProjects
$map['queryProjects']['access'] = Config::$ACCESS_LEVEL_USER;
//Ruta de deleteProjects
$map['deleteProjects']['access'] = Config::$ACCESS_LEVEL_USER;
//Ruta de createTaskListItemListItems
$map['createTaskListItemListItems']['access'] = Config::$ACCESS_LEVEL_USER;
//Ruta de updateTaskListItemListItems
$map['updateTaskListItemListItems']['access'] = Config::$ACCESS_LEVEL_USER;
//Ruta de queryTaskListItemListItems
$map['queryTaskListItemListItems']['access'] = Config::$ACCESS_LEVEL_USER;
//Ruta de deleteTaskListItemListItems
$map['deleteTaskListItemListItems']['access'] = Config::$ACCESS_LEVEL_USER;
//Ruta de createTaskListItemLists
$map['createTaskListItemLists']['access'] = Config::$ACCESS_LEVEL_USER;
//Ruta de updateTaskListItemLists
$map['updateTaskListItemLists']['access'] = Config::$ACCESS_LEVEL_USER;
//Ruta de queryTaskListItemLists
$map['queryTaskListItemLists']['access'] = Config::$ACCESS_LEVEL_USER;
//Ruta de deleteTaskListItemLists
$map['deleteTaskListItemLists']['access'] = Config::$ACCESS_LEVEL_USER;
//Ruta de createTaskLists
$map['createTaskLists']['access'] = Config::$ACCESS_LEVEL_USER;
//Ruta de updateTaskLists
$map['updateTaskLists']['access'] = Config::$ACCESS_LEVEL_USER;
//Ruta de queryTaskLists
$map['queryTaskLists']['access'] = Config::$ACCESS_LEVEL_USER;
//Ruta de deleteTaskLists
$map['deleteTaskLists']['access'] = Config::$ACCESS_LEVEL_USER;
//Ruta de createTaskListsOrderCriteria
$map['createTaskListsOrderCriteria']['access'] = Config::$ACCESS_LEVEL_USER;
//Ruta de updateTaskListsOrderCriteria
$map['updateTaskListsOrderCriteria']['access'] = Config::$ACCESS_LEVEL_USER;
//Ruta de queryTaskListsOrderCriteria
$map['queryTaskListsOrderCriteria']['access'] = Config::$ACCESS_LEVEL_USER;
//Ruta de deleteTaskListsOrderCriteria
$map['deleteTaskListsOrderCriteria']['access'] = Config::$ACCESS_LEVEL_USER;
//Ruta de createUsers
$map['createUsers']['access'] = Config::$ACCESS_LEVEL_USER;
//Ruta de updateUsers
$map['updateUsers']['access'] = Config::$ACCESS_LEVEL_USER;
//Ruta de queryUsers
$map['queryUsers']['access'] = Config::$ACCESS_LEVEL_USER;
//Ruta de deleteUsers
$map['deleteUsers']['access'] = Config::$ACCESS_LEVEL_USER;
//Ruta de createBookmarked
$map['createBookmarked']['access'] = Config::$ACCESS_LEVEL_USER;
//Ruta de updateBookmarked
$map['updateBookmarked']['access'] = Config::$ACCESS_LEVEL_USER;
//Ruta de queryBookmarked
$map['queryBookmarked']['access'] = Config::$ACCESS_LEVEL_USER;
//Ruta de deleteBookmarked
$map['deleteBookmarked']['access'] = Config::$ACCESS_LEVEL_USER;
//Ruta de createBookmarkedDashboards
$map['createBookmarkedDashboards']['access'] = Config::$ACCESS_LEVEL_USER;
//Ruta de updateBookmarkedDashboards
$map['updateBookmarkedDashboards']['access'] = Config::$ACCESS_LEVEL_USER;
//Ruta de queryBookmarkedDashboards
$map['queryBookmarkedDashboards']['access'] = Config::$ACCESS_LEVEL_USER;
//Ruta de deleteBookmarkedDashboards
$map['deleteBookmarkedDashboards']['access'] = Config::$ACCESS_LEVEL_USER;
//Ruta de createDashboardItem
$map['createDashboardItem']['access'] = Config::$ACCESS_LEVEL_USER;
//Ruta de updateDashboardItem
$map['updateDashboardItem']['access'] = Config::$ACCESS_LEVEL_USER;
//Ruta de queryDashboardItem
$map['queryDashboardItem']['access'] = Config::$ACCESS_LEVEL_USER;
//Ruta de deleteDashboardItem
$map['deleteDashboardItem']['access'] = Config::$ACCESS_LEVEL_USER;
//Ruta de disableDashboardItem
$map['disableDashboardItem']['access'] = Config::$ACCESS_LEVEL_USER;
//Ruta de createDashboardList
$map['createDashboardList']['access'] = Config::$ACCESS_LEVEL_USER;
//Ruta de updateDashboardList
$map['updateDashboardList']['access'] = Config::$ACCESS_LEVEL_USER;
//Ruta de queryDashboardList
$map['queryDashboardList']['access'] = Config::$ACCESS_LEVEL_USER;
//Ruta de deleteDashboardList
$map['deleteDashboardList']['access'] = Config::$ACCESS_LEVEL_USER;
//Ruta de createDashboardListOrderCriteria
$map['createDashboardListOrderCriteria']['access'] = Config::$ACCESS_LEVEL_USER;
//Ruta de updateDashboardListOrderCriteria
$map['updateDashboardListOrderCriteria']['access'] = Config::$ACCESS_LEVEL_USER;
//Ruta de queryDashboardListOrderCriteria
$map['queryDashboardListOrderCriteria']['access'] = Config::$ACCESS_LEVEL_USER;
//Ruta de deleteDashboardListOrderCriteria
$map['deleteDashboardListOrderCriteria']['access'] = Config::$ACCESS_LEVEL_USER;
//Ruta de createRoles
$map['createRoles']['access'] = Config::$ACCESS_LEVEL_USER;
//Ruta de updateRoles
$map['updateRoles']['access'] = Config::$ACCESS_LEVEL_USER;
//Ruta de queryRoles
$map['queryRoles']['access'] = Config::$ACCESS_LEVEL_USER;
//Ruta de deleteRoles
$map['deleteRoles']['access'] = Config::$ACCESS_LEVEL_USER;
//Ruta de getProjectCollaborationRoles
$map['getProjectCollaborationRoles']['access'] = Config::$ACCESS_LEVEL_USER;
//Ruta de createProjectDiaryModification
$map['createProjectDiaryModification']['access'] = Config::$ACCESS_LEVEL_USER;
//Ruta de updateProjectDiaryModification
$map['updateProjectDiaryModification']['access'] = Config::$ACCESS_LEVEL_USER;
//Ruta de queryProjectDiaryModification
$map['queryProjectDiaryModification']['access'] = Config::$ACCESS_LEVEL_USER;
//Ruta de deleteProjectDiaryModification
$map['deleteProjectDiaryModification']['access'] = Config::$ACCESS_LEVEL_USER;
//profile
$map['profile']['access'] = Config::$ACCESS_LEVEL_USER;
$map['createDashboardsItemAssignation']['access'] = Config::$ACCESS_LEVEL_USER;
$map['updateDashboardsItemAssignation']['access'] = Config::$ACCESS_LEVEL_USER;
$map['queryDashboardsItemAssignation']['access'] = Config::$ACCESS_LEVEL_USER;
$map['deleteDashboardsItemAssignation']['access'] = Config::$ACCESS_LEVEL_USER;
$map['getAssignedDashboardItems']['access'] = Config::$ACCESS_LEVEL_USER;
//updateOrderInDashboardList
$map['updateOrderInDashboardList']['access'] = Config::$ACCESS_LEVEL_USER;
//searchUsers
$map['searchUsers']['access'] = Config::$ACCESS_LEVEL_USER;
//getDashboardItemDetails
$map['getDashboardItemDetails']['access'] = Config::$ACCESS_LEVEL_USER;
//about
$map['about']['access'] = Config::$ACCESS_LEVEL_GUEST;